parameters:
    admin_prefix:     '%env(resolve:ADMIN_PREFIX)%'
    asset.request_context.secure: true
    container.dumper.inline_factories: true
    container.dumper.inline_class_loader: true
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false
        bind:
            $adminPrefix: '%admin_prefix%'
            $appEnv: '%kernel.environment%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Infrastructure/Migrations,Tests,Kernel.php}'
    Redis:
        class: Predis\Client
        arguments:
            - '%env(REDIS_URL)%'

    Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler:
        arguments:
            - '@Redis'

    App\Http\Controller\:
        resource: '../src/Http/Controller'
        tags: ['controller.service_arguments']

    App\Http\Admin\Controller\:
        resource: '../src/Http/Admin/Controller'
        tags: ['controller.service_arguments']

    App\Http\Api\Controller\:
        resource: '../src/Http/Api/Controller'
        tags: ['controller.service_arguments']


    App\Http\Admin\Firewall\AdminRequestListener:
        arguments: ['%admin_prefix%']

    Knp\Bundle\PaginatorBundle\Helper\Processor: ~

    App\Http\Helper\Paginator\PaginatorInterface:
        class: App\Http\Helper\Paginator\Paginator

    App\Http\Twig\TwigAssetExtension:
        arguments:
            $assetPath: '%kernel.project_dir%/public/assets'
            $env: '%kernel.environment%'

    App\Infrastructure\Queue\FailedJobsService:
        arguments: ['@messenger.transport.failed']

    App\Infrastructure\Queue\ScheduledJobsService:
        arguments:
            $dsn: '%env(MESSENGER_TRANSPORT_DSN)%'

    App\Infrastructure\Mercure\Service\CookieGenerator:
        arguments:
            $secret: '%env(resolve:MERCURE_SUBSCRIBER_KEY)%'

